name: Bump scaffold

on:
  workflow_dispatch:
    inputs:
      package-name:
        default: $package-name
        description: Name of the package
        required: true
        type: string
      use-react:
        default: $use-react
        description: Use React
        required: true
        type: boolean

jobs:
  call-workflow:
    secrets: inherit
    uses: compulim/workflows/.github/workflows/bump-scaffold.yml@main
    with:
      package-name: $package-name
      use-react: $use-react
