name: Publish release

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to publish

jobs:
  call-workflow:
    permissions:
      contents: write
      pages: write
      id-token: write
    secrets: inherit
    uses: compulim/workflows/.github/workflows/publish-release.yml@main
    with:
      package-name: $package-name
      tag: ${{ inputs.tag || github.ref }}
