name: Pull request validation

on:
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  call-workflow:
    strategy:
      matrix:
        node-version: lts/*
        switch: [current, react-16, react-17, react-18]
    uses: compulim/workflows/.github/workflows/pull-request-validation.yml@main
    with:
      node-version: ${{ matrix.node-version }}
      package-name: $package-name
      skip-integration-test: $skip-integration-test
      switch: ${{ matrix.switch }}
