name: Pull request validation

on:
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  call-workflow:
    strategy:
      matrix:
        react-version: ["", 16, 17, 18, latest]
    uses: compulim/workflows/.github/workflows/pull-request-validation.yml@main
    with:
      package-name: $package-name
      react-version: ${{ matrix.react-version }}
      skip-integration-test: $skip-integration-test
