extends:
  - ./.eslintrc.custom.yml
ignorePatterns:
  - test/webDriver/static/**
overrides:
  - env:
      commonjs: true
    files:
      - '**/*.js'
  - env:
      esm: true
    files:
      - '**/*.mjs'
