name: List outdated dependencies

on:
  workflow_call: {}

defaults:
  run:
    shell: bash

env:
  node-version: lts

jobs:
  list-outdated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ env.node-version }}
          cache: npm

      - name: Install packages
        run: |
          for i in `find . -name package.json ! -path */node_modules/* | xargs realpath | xargs dirname`
          do
            echo --- $i/package.json ---
            cd $i
            npm run prebump --if-present
            npm install --ignore-scripts
            npm run postbump --if-present
            cd $OLDPWD
            echo
          done

      - name: Audit packages
        run: |
          echo \`\`\` | tee --append $GITHUB_STEP_SUMMARY

          for i in `find . -name package.json ! -path */node_modules/* | xargs realpath | xargs dirname`
          do
            echo --- $i/package.json --- | tee --append $GITHUB_STEP_SUMMARY
            cd $i
            npm audit | tee --append $GITHUB_STEP_SUMMARY || true
            cd $OLDPWD
            echo | tee --append $GITHUB_STEP_SUMMARY
          done

          echo \`\`\` | tee --append $GITHUB_STEP_SUMMARY

      - name: List outdated packages
        run: |
          echo \`\`\` | tee --append $GITHUB_STEP_SUMMARY

          for i in `find . -name package.json ! -path */node_modules/* | xargs realpath | xargs dirname`
          do echo --- $i/package.json --- | tee --append $GITHUB_STEP_SUMMARY
            cd $i
            npm outdated | tee --append $GITHUB_STEP_SUMMARY || true
            cd $OLDPWD
            echo | tee --append $GITHUB_STEP_SUMMARY
          done

          echo \`\`\` | tee --append $GITHUB_STEP_SUMMARY
