name: Prepare release

on:
  workflow_call: {}

defaults:
  run:
    shell: bash

env:
  node-version: latest

jobs:
  pull-request:
    environment:
      name: workflow-bot
      url: https://github.com/${{ github.repository }}/pull/${{ steps.pull-request.outputs.pull-request-number }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - id: generate-token
        name: Generate token for workflow-bot
        uses: compulim/tibdex-github-app-token@v2.1.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - uses: actions/checkout@main
      - name: Configure user profile
        run: |
          git config user.email "${{ format('@{0}', github.actor) }}"
          git config user.name "${{ format('@{0}', github.actor) }}"
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ env.node-version }}
          cache: npm
      - id: version
        run: |
          npm version patch --no-git-tag-version

          echo version=$(cat package.json | jq -r .version) | tee --append $GITHUB_OUTPUT
      - name: Create branch
        id: branch
        run: |
          BRANCH_NAME=bot/prepare-release/${{ steps.version.outputs.version }}
          echo branch-name=$BRANCH_NAME | tee --append $GITHUB_OUTPUT

          git checkout -b $BRANCH_NAME
      - name: Update CHANGELOG.md
        run: npx keep-a-changelog --format markdownlint --release ${{ steps.version.outputs.version }}
      - name: Stage changes
        run: git add --all --verbose
      - name: Commit changes
        run: git commit --message "v${{ steps.version.outputs.version }}"
      - name: Push to branch
        run: git push --set-upstream origin ${{ steps.branch.outputs.branch-name }}
      - env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        id: pull-request
        name: Create pull request
        run: |
          gh api repos/${{ github.repository }}/pulls \
            --field base=main \
            --field head=${{ steps.branch.outputs.branch-name }} \
            --field title="${{ steps.version.outputs.version }} Release" \
            | tee /tmp/pull-request.json
          echo pull-request-number=$(cat /tmp/pull-request.json | jq -r '.number') | tee --append $GITHUB_OUTPUT
      - continue-on-error: true
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        name: Assign pull request ${{ steps.pull-request.outputs.pull-request-number }} to ${{ github.actor }}
        run: |
          gh api repos/${{ github.repository }}/issues/${{ steps.pull-request.outputs.pull-request-number }}/assignees \
            --field assignees[]=${{ github.actor }}
      - continue-on-error: true
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        name: Add label "release" to pull request ${{ steps.pull-request.outputs.pull-request-number }}
        run: |
          gh api repos/${{ github.repository }}/issues/${{ steps.pull-request.outputs.pull-request-number }}/labels \
            --field labels[]=release
