name: Prepare release

on:
  workflow_call:
    outputs:
      pull-request-url:
        value: ${{ jobs.create-pull-request.outputs.url }}
      version:
        value: ${{ jobs.create-pull-request.outputs.version }}
    secrets:
      GH_TOKEN:
        description: Token for GH CLI with Read and Write access to code, pull requests, and workflows
        required: true

defaults:
  run:
    shell: bash

env:
  node-version: 18.x

jobs:
  create-pull-request:
    environment:
      name: admin
      url: https://github.com/${{ github.repository }}/pull/${{ steps.pull-request.outputs.pull-request-number }}
    outputs:
      url: https://github.com/${{ github.repository }}/pull/${{ steps.pull-request.outputs.pull-request-number }}
      version: ${{ steps.version.outputs.version }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure user profile
        run: |
          git config user.email "${{ format('@{0}', github.actor) }}"
          git config user.name "${{ format('@{0}', github.actor) }}"
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'
      - id: version
        run: |
          npm version patch --no-git-tag-version
          echo version=$(cat package.json | jq -r .version) | tee --append $GITHUB_OUTPUT
      - name: Create branch
        id: branch
        run: |
          BRANCH_NAME=bot/prepare-release/${{ steps.version.outputs.version }}
          echo branch-name=$BRANCH_NAME | tee --append $GITHUB_OUTPUT

          git checkout -b $BRANCH_NAME
      - name: Update CHANGELOG.md
        run: npx keep-a-changelog --release ${{ steps.version.outputs.version }}
      - name: Stage changes
        run: git add --all --verbose
      - name: Commit changes
        run: git commit --message "v${{ steps.version.outputs.version }}"
      - name: Push to branch
        run: git push --set-upstream origin ${{ steps.branch.outputs.branch-name }}
      - env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        id: pull-request
        name: Create pull request
        run: |
          gh api repos/${{ github.repository }}/pulls --field base=main --field head=${{ steps.branch.outputs.branch-name }} --field title="${{ steps.version.outputs.version }} Release" | tee /tmp/pull-request.json
          echo pull-request-number=$(cat /tmp/pull-request.json | jq -r '.number') | tee --append $GITHUB_OUTPUT
      - env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        name: Assign pull request ${{ steps.pull-request.outputs.pull-request-number }} to ${{ github.actor }}
        run: gh api repos/${{ github.repository }}/issues/${{ steps.pull-request.outputs.pull-request-number }}/assignees --field assignees[]=${{ github.actor }}
      - continue-on-error: true
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        name: Add label "release" to pull request ${{ steps.pull-request.outputs.pull-request-number }}
        run: gh api repos/${{ github.repository }}/issues/${{ steps.pull-request.outputs.pull-request-number }}/labels --field labels[]=release
