name: Publish release

on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      GH_TOKEN: {}
      NPM_TOKEN: {}

defaults:
  run:
    shell: bash

env:
  node-version: 18.x

jobs:
  publish-package:
    environment:
      name: production
      url: https://npmjs.com/package/${{ steps.package-json.outputs.package-name }}/v/${{ steps.package-json.outputs.version }}
    outputs:
      url: https://npmjs.com/package/${{ steps.package-json.outputs.package-name }}/v/${{ steps.package-json.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          registry-url: https://registry.npmjs.org/
      - env:
          GH_TOKEN: ${{ github.token }}
        name: Download assets
        run: gh release download ${{ inputs.tag }} --repo ${{ github.repository }}
      - id: package-json
        name: Read package.json
        run: |
          echo package-name=`tar --extract --file=\`ls ./*.tgz\` --to-stdout package/package.json | jq -r .name` | tee --append $GITHUB_OUTPUT
          echo version=`tar --extract --file=\`ls ./*.tgz\` --to-stdout package/package.json | jq -r .version` | tee --append $GITHUB_OUTPUT
      - if: ${{ contains(steps.package-json.outputs.version, '-') }}
        name: 'Sanity check: Must not prerelease'
        run: '[[ "${{ steps.package-json.outputs.version }}" != *-0 ]]'
      # - env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      #   run: npm publish `ls ./*.tgz`

  create-pull-request:
    continue-on-error: true
    environment:
      name: admin
      url: ${{ steps.summary.outputs.url }}
    outputs:
      url: ${{ steps.summary.outputs.url }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure user profile
        run: |
          git config user.email "${{ format('@{0}', github.actor) }}"
          git config user.name "${{ format('@{0}', github.actor) }}"
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'
      - id: version
        run: |
          npm version prepatch --no-git-tag-version
          echo version=$(cat package.json | jq -r .version) | tee --append $GITHUB_OUTPUT
      - name: Create branch
        id: branch
        run: |
          BRANCH_NAME=bot/publish-release/${{ steps.version.outputs.version }}
          echo branch-name=$BRANCH_NAME | tee --append $GITHUB_OUTPUT

          git checkout -b $BRANCH_NAME
      - name: Stage changes
        run: git add --all --verbose
      - name: Commit changes
        run: git commit --message "v${{ steps.version.outputs.version }}"
      - name: Push to branch
        run: git push --set-upstream origin ${{ steps.branch.outputs.branch-name }}
      - env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        id: pull-request
        name: Create pull request
        run: |
          gh api repos/${{ github.repository }}/pulls --field base=main --field head=${{ steps.branch.outputs.branch-name }} --field title="Bump to ${{ steps.version.outputs.version }}" | tee /tmp/pull-request.json
          echo pull-request-number=$(cat /tmp/pull-request.json | jq -r '.number') | tee --append $GITHUB_OUTPUT
      - continue-on-error: true
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        name: Assign pull request ${{ steps.pull-request.outputs.pull-request-number }} to ${{ github.actor }}
        run: gh api repos/${{ github.repository }}/issues/${{ steps.pull-request.outputs.pull-request-number }}/assignees --field assignees[]=${{ github.actor }}
      - continue-on-error: true
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        name: Add label "release" to pull request ${{ steps.pull-request.outputs.pull-request-number }}
        run: gh api repos/${{ github.repository }}/issues/${{ steps.pull-request.outputs.pull-request-number }}/labels --field labels[]=release
